# Creating a logictic regresssion to predict absenteeism

## Import the relevant libraries

In [5]:
import pandas as pd
import numpy as np

## Load the preprocessed dataset

In [6]:
!pwd

/Users/noe/Documents/Data_science/UDEMY/Projects_2022/Absenteism/Machine_learning


In [7]:
data_preprocessed = pd.read_csv('../Preprocessing/Absenteeism_preprocessed.csv')

## Create the targets

In [8]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [9]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [10]:
data_preprocessed['Excessive_absenteeism'] = targets
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Absenteeism Time in Hours  \
0               30          0         2     1                          4   
1               31          0         1     0                          0   
2               31          0         0     0                          2   
3               24          0         2     0                          4   
4               30          0         2     1                          2   

   Excessive_absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [11]:
# note that a balance of 60 - 40 split is good !!!

In [12]:
data_with_targets = data_preprocessed.drop('Absenteeism Time in Hours',axis = 1)
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pets  Excessive_absenteeism  
0               30          0         2     1                      1  
1               31          0         1     0                      0  
2               31          0         0     0                      0  
3               24          0         2     0                      1  
4               30          0         2     1                      0

## Select the input for the regression

In [13]:
data_with_targets.shape

(700, 15)

In [14]:
data_with_targets.iloc[:,:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month value  Day of the week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pets  
0                 30          0         2     1  
1                 31          0         1     0  
2                 31          0         0     0  
3                 24          0         2     0  
4                 30          0         2     1  
..               ...        ...       ...   ...  
695               22          1         2     0  
696               24          0         1     2  
697               25          1         0     0  
698               25          1         0     0  
699               25          0         1     1  

[700 rows x 14 columns]

In [15]:
# Another and better way
unscaled_inputs = data_with_targets.iloc[:,:-1]

## Standardize the inputs
Let us choose the columns to scale.

In [32]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [83]:
columns_to_scale = ['Month value','Day of the week', 'Transportation Expense', 'Month value',
       'Age', 'Daily Work Load Average', 'Body Mass Index','Children', 'Pets', 'Education', 'Distance to Work']

In [84]:
from sklearn.preprocessing import StandardScaler
absenteeism_scaler = StandardScaler()

In [85]:
absenteeism_scaler.fit(unscaled_inputs[columns_to_scale])

StandardScaler()

In [86]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs[columns_to_scale])

In [429]:
Reasons = unscaled_inputs[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']].to_numpy()

In [430]:
scaled_inputs = np.concatenate((Reasons,scaled_inputs),axis=1)

In [87]:
scaled_inputs

array([[ 0.18272635, -0.68370352,  1.00584437, ...,  0.26848661,
        -0.44798003,  0.41281584],
       [ 0.18272635, -0.68370352, -1.57468098, ..., -0.58968976,
        -0.44798003, -1.1418824 ],
       [ 0.18272635, -0.00772546, -0.6541427 , ..., -0.58968976,
        -0.44798003,  1.42674947],
       ...,
       [-0.3882935 ,  0.66825259,  1.62456682, ..., -0.58968976,
         2.23224237, -0.93909568],
       [-0.3882935 ,  0.66825259,  0.19094163, ..., -0.58968976,
         2.23224237, -0.93909568],
       [-0.3882935 ,  0.66825259,  1.03602595, ...,  0.26848661,
        -0.44798003,  0.07483796]])

In [88]:
scaled_inputs.shape

(700, 11)

## Split the data into train and test and split the data

### Import the relevant modules

In [89]:
from sklearn.model_selection import train_test_split

### Split

In [90]:
train_test_split(scaled_inputs,targets)

[array([[ 0.7537462 ,  0.66825259,  0.19094163, ..., -0.58968976,
         -0.44798003, -0.66871337],
        [-0.95931334, -0.00772546,  2.21310769, ..., -0.58968976,
         -0.44798003, -0.8715001 ],
        [ 1.03925612,  0.66825259,  0.38712192, ...,  0.26848661,
         -0.44798003, -0.33073549],
        ...,
        [ 0.46823627,  0.66825259,  1.62456682, ..., -0.58968976,
          2.23224237, -0.93909568],
        [-0.67380342, -0.68370352, -0.6541427 , ..., -0.58968976,
          2.23224237, -0.53352222],
        [ 1.32476605, -0.00772546,  0.56821142, ..., -0.58968976,
         -0.44798003,  1.3591539 ]]),
 array([[-0.67380342,  1.34423065,  0.35694034, ..., -0.58968976,
         -0.44798003, -0.33073549],
        [ 0.7537462 , -0.68370352, -0.6541427 , ..., -0.58968976,
         -0.44798003,  1.42674947],
        [ 1.32476605,  0.66825259,  0.38712192, ...,  0.26848661,
         -0.44798003, -0.33073549],
        ...,
        [-1.24482327,  0.66825259,  0.04003371, ...,  

In [91]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs,targets,train_size=0.8,random_state=20)

In [92]:
print(x_train.shape,y_train.shape)

(560, 11) (560,)


In [93]:
print(x_test.shape,y_test.shape)

(140, 11) (140,)


# Logistic regression with sklearn

In [94]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [95]:
reg = LogisticRegression()

In [96]:
reg.fit(x_train,y_train)

LogisticRegression()

In [97]:
reg.score(x_train,y_train)

0.6589285714285714

In [98]:
model_output = reg.predict(x_train)
model_output

array([0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,

In [99]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [100]:
model_output == y_train

array([ True,  True, False, False, False, False,  True,  True,  True,
        True,  True, False, False, False,  True, False,  True,  True,
       False,  True,  True,  True,  True, False, False,  True,  True,
        True, False,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False, False,  True,  True, False,
        True, False, False,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True, False, False, False, False, False,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [101]:
# Number of true entries
np.sum(model_output == y_train)

369

In [102]:
model_output.shape[0]

560

In [103]:
np.sum(model_output == y_train)/model_output.shape[0]

0.6589285714285714

## Finding the intercept and coefficients

In [104]:
reg.intercept_

array([-0.20256405])

In [105]:
reg.coef_

array([[ 0.08439415, -0.19370639,  0.54230901,  0.08439415, -0.07526605,
         0.14049988,  0.16086827,  0.31145703, -0.22956945,  0.06670154,
        -0.03149193]])

In [106]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [107]:
feature_names = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month value',
       'Day of the week', 'Transportation Expense', 'Body Mass Index','Children', 'Pets']

In [108]:
summary_table = pd.DataFrame(columns=['Feature name'], data = columns_to_scale)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

Feature name  Coefficient
0               Month value     0.084394
1           Day of the week    -0.193706
2    Transportation Expense     0.542309
3               Month value     0.084394
4                       Age    -0.075266
5   Daily Work Load Average     0.140500
6           Body Mass Index     0.160868
7                  Children     0.311457
8                      Pets    -0.229569
9                 Education     0.066702
10         Distance to Work    -0.031492

In [109]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['intercept',reg.intercept_[0]]
summary_table     = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                 intercept    -0.202564
1               Month value     0.084394
2           Day of the week    -0.193706
3    Transportation Expense     0.542309
4               Month value     0.084394
5                       Age    -0.075266
6   Daily Work Load Average     0.140500
7           Body Mass Index     0.160868
8                  Children     0.311457
9                      Pets    -0.229569
10                Education     0.066702
11         Distance to Work    -0.031492

# Interpreting the coefficients

In [110]:
summary_table['Odd_ratio'] = np.exp(summary_table.Coefficient)

In [111]:
summary_table

Feature name  Coefficient  Odd_ratio
0                 intercept    -0.202564   0.816634
1               Month value     0.084394   1.088058
2           Day of the week    -0.193706   0.823900
3    Transportation Expense     0.542309   1.719974
4               Month value     0.084394   1.088058
5                       Age    -0.075266   0.927497
6   Daily Work Load Average     0.140500   1.150849
7           Body Mass Index     0.160868   1.174530
8                  Children     0.311457   1.365413
9                      Pets    -0.229569   0.794876
10                Education     0.066702   1.068976
11         Distance to Work    -0.031492   0.968999

In [112]:
summary_table.sort_values('Odd_ratio',ascending=False)

Feature name  Coefficient  Odd_ratio
3    Transportation Expense     0.542309   1.719974
8                  Children     0.311457   1.365413
7           Body Mass Index     0.160868   1.174530
6   Daily Work Load Average     0.140500   1.150849
1               Month value     0.084394   1.088058
4               Month value     0.084394   1.088058
10                Education     0.066702   1.068976
11         Distance to Work    -0.031492   0.968999
5                       Age    -0.075266   0.927497
2           Day of the week    -0.193706   0.823900
0                 intercept    -0.202564   0.816634
9                      Pets    -0.229569   0.794876

Note that coefficient around zero & odd ratio around one means that the feature is not particularly important
In that regard, `Daily Work Load Average`, `Distance to Work`, as well as `Day of the week`, `Education`, `Age 	`, seems to be the features with the most insignificant coefficients.

# Searching for a simpler model

# Testing the model

In [113]:
reg.score(x_test,y_test)

0.6071428571428571

In [114]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.6656773 , 0.3343227 ],
       [0.47578   , 0.52422   ],
       [0.28907071, 0.71092929],
       [0.77503463, 0.22496537],
       [0.2597199 , 0.7402801 ],
       [0.67110701, 0.32889299],
       [0.67373888, 0.32626112],
       [0.48180565, 0.51819435],
       [0.67475618, 0.32524382],
       [0.67290103, 0.32709897],
       [0.37046163, 0.62953837],
       [0.15198592, 0.84801408],
       [0.33528702, 0.66471298],
       [0.47344008, 0.52655992],
       [0.62907703, 0.37092297],
       [0.43738079, 0.56261921],
       [0.44153301, 0.55846699],
       [0.41189626, 0.58810374],
       [0.64051156, 0.35948844],
       [0.25198806, 0.74801194],
       [0.53116582, 0.46883418],
       [0.75138637, 0.24861363],
       [0.65114578, 0.34885422],
       [0.70805616, 0.29194384],
       [0.69084813, 0.30915187],
       [0.56133213, 0.43866787],
       [0.42182417, 0.57817583],
       [0.71837722, 0.28162278],
       [0.5734337 , 0.4265663 ],
       [0.72613064, 0.27386936],
       [0.

In [115]:
predicted_proba.shape

(140, 2)

In [116]:
# Probability of excessive absenteism
predicted_proba[:,1]

array([0.3343227 , 0.52422   , 0.71092929, 0.22496537, 0.7402801 ,
       0.32889299, 0.32626112, 0.51819435, 0.32524382, 0.32709897,
       0.62953837, 0.84801408, 0.66471298, 0.52655992, 0.37092297,
       0.56261921, 0.55846699, 0.58810374, 0.35948844, 0.74801194,
       0.46883418, 0.24861363, 0.34885422, 0.29194384, 0.30915187,
       0.43866787, 0.57817583, 0.28162278, 0.4265663 , 0.27386936,
       0.49184357, 0.43788541, 0.45083529, 0.65709552, 0.24861363,
       0.57787947, 0.30208894, 0.40860998, 0.57701353, 0.62800315,
       0.35122686, 0.2671527 , 0.34222264, 0.68572802, 0.50583157,
       0.21758092, 0.3300862 , 0.39535181, 0.29039824, 0.26649659,
       0.41750874, 0.75744438, 0.39679128, 0.46245492, 0.6071712 ,
       0.66403281, 0.55800166, 0.41426363, 0.60980217, 0.56491844,
       0.49822477, 0.32200081, 0.46288551, 0.38957538, 0.321985  ,
       0.35019052, 0.27260022, 0.39154805, 0.34715505, 0.57006685,
       0.3312156 , 0.74121279, 0.65715093, 0.52653037, 0.69223

# Saving the ML model & preparing it for future use

In [117]:
import pickle

In [118]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [119]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)

# Deploying the model on a new dataset

In [120]:
!pwd

/Users/noe/Documents/Data_science/UDEMY/Projects_2022/Absenteism/Machine_learning


In [121]:
# import data
df = pd.read_csv('/Users/noe/Documents/Data_science/UDEMY/Projects_2022/Absenteism/Integration/Absenteeism_new_data.csv')
df.head()

ID  Reason for Absence        Date  Transportation Expense  \
0  22                  27  01/06/2018                     179   
1  10                   7  04/06/2018                     361   
2  14                  23  06/06/2018                     155   
3  17                  25  08/06/2018                     179   
4  14                  10  08/06/2018                     155   

   Distance to Work  Age  Daily Work Load Average  Body Mass Index  Education  \
0                26   30                  237.656               19          3   
1                52   28                  237.656               27          1   
2                12   34                  237.656               25          1   
3                22   40                  237.656               22          2   
4                12   34                  237.656               25          1   

   Children  Pets  
0         0     0  
1         1     4  
2         2     0  
3         2     0  
4         2     0

In [122]:
df = df.drop('ID',axis=1)

In [123]:
reasons = pd.get_dummies(df['Reason for Absence'])
reasons = reasons.drop([0],axis=1)
reasons

6   7   8   10  11  13  14  19  22  23  25  26  27  28
0    0   0   0   0   0   0   0   0   0   0   0   0   1   0
1    0   1   0   0   0   0   0   0   0   0   0   0   0   0
2    0   0   0   0   0   0   0   0   0   1   0   0   0   0
3    0   0   0   0   0   0   0   0   0   0   1   0   0   0
4    0   0   0   1   0   0   0   0   0   0   0   0   0   0
5    0   0   0   0   1   0   0   0   0   0   0   0   0   0
6    0   1   0   0   0   0   0   0   0   0   0   0   0   0
7    0   0   0   0   0   0   0   0   0   0   0   0   1   0
8    0   0   0   0   0   0   0   0   0   0   0   1   0   0
9    0   0   0   1   0   0   0   0   0   0   0   0   0   0
10   0   0   0   0   0   0   0   0   1   0   0   0   0   0
11   0   0   0   0   0   0   0   1   0   0   0   0   0   0
12   0   0   0   0   0   0   0   1   0   0   0   0   0   0
13   0   0   0   0   0   0   0   0   0   0   0   0   1   0
14   0   0   0   0   0   0   0   0   0   0   0   0   0   0
15   0   0   0   0   0   0   0   0   0   0   0   0   0   0
16   0   0   0   0   0   0   0   1   0   0   0   0   0   0
17   0   0   0   0   0   1   0   0   0   0   0   0   0   0
18   0   0   0   0   0   0   0   0   0   0   0   0   0   1
19   0   0   0   0   0   1   0   0   0   0   0   0   0   0
20   0   0   0   0   0   0   0   0   0   0   1   0   0   0
21   0   0   0   0   0   0   0   0   1   0   0   0   0   0
22   0   0   1   0   0   0   0   0   0   0   0   0   0   0
23   0   0   0   1   0   0   0   0   0   0   0   0   0   0
24   0   0   0   0   0   0   0   0   1   0   0   0   0   0
25   0   0   0   0   0   0   0   0   0   0   0   1   0   0
26   0   0   0   0   0   0   0   1   0   0   0   0   0   0
27   1   0   0   0   0   0   0   0   0   0   0   0   0   0
28   0   0   0   0   0   0   0   0   0   0   0   0   0   1
29   1   0   0   0   0   0   0   0   0   0   0   0   0   0
30   0   0   0   0   0   0   0   0   1   0   0   0   0   0
31   0   0   0   0   0   0   0   0   0   1   0   0   0   0
32   0   0   0   0   0   0   0   0   1   0   0   0   0   0
33   0   0   0   0   0   0   0   0   1   0   0   0   0   0
34   0   0   0   0   0   1   0   0   0   0   0   0   0   0
35   0   0   0   0   0   0   1   0   0   0   0   0   0   0
36   0   0   0   0   1   0   0   0   0   0   0   0   0   0
37   0   0   0   0   0   0   0   0   0   0   0   0   0   0
38   0   0   0   0   0   0   0   0   0   0   0   0   0   0
39   0   0   0   0   0   0   0   0   0   0   0   0   0   0

In [124]:
columns_to_scale_nd = df.columns.values
columns_to_scale_nd

array(['Reason for Absence', 'Date', 'Transportation Expense',
       'Distance to Work', 'Age', 'Daily Work Load Average',
       'Body Mass Index', 'Education', 'Children', 'Pets'], dtype=object)

In [125]:
# Scale the data
absenteeism_scaler.fit(df[columns_to_scale])
scaled_inputs_nd = absenteeism_scaler.transform(df[columns_to_scale])
Reasons = df[['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4']].to_numpy()
scaled_inputs_nd = np.concatenate((Reasons,scaled_inputs_nd),axis=1)

KeyError: "['Month value', 'Day of the week'] not in index"

In [ ]:
pickled_model = pickle.load(open('model', 'rb'))
pickled_model.predict(X_test)